/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cookies.h"

bool_t
xdr_CookieStruct (XDR *xdrs, CookieStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->CanHaveCookie))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->JudyOrTina))
		 return FALSE;
	return TRUE;
}
